### ISSUE TITLE
Is ReactMounter deprecated?

### ISSUE THREAD

**Issue by ruaneg** [helpscout/brigade#19]
Hi,

Im looking into using your very nice library. It seems that ReactMounter is deprecated according to the documentation, is that correct?
https://brigade.netlify.com/react-mounter

Cheers
Gary

**Comment by knicklabs** [comment]
Hi @ruaneg, #20 removes the deprecation notice from the documentation as we have found ReactMounter continues to be useful in some cases. From the updated documentation:

> ReactMounter is ideally suited for mounting one or more complex React components or entire React applications inside a Backbone or Marionette View, particularly where all of the business logic and state is controlled in the Backbone or Marionette app and you are interested in syncing its state with React components or apps.

If you are using Marionette and using the Redux architecture with React I would encourage you to check out StatefulReactView as an alternative to ReactMounter.

Cheers,

Nickolas

**Comment by ruaneg** [comment]
Hi Nikolas,

I'm using custom modified Backbone and didn't manage to get ReactMounter working. Ill try it again next week and see if I can debug it to find out where its going wrong.

Note: I also had to add 'backbone.marionette' to my package.json event though I was only trying to use ReactMounter. 

Cheers
Gary

**Comment by knicklabs** [comment]
@ruaneg Thanks for these questions. It provided me with an opportunity to update our docs and make them better.

ReactMounter is compatible with Backbone views but it does require a bit of coercing. We rely on a `render` event which Marionette Views have baked in but it's possible to add this to Backbone views. 

To get it to work, the render method on the Backbone view needs to call `this.trigger('render')` after updating the DOM. I added a `Usage with Backbone Views` section to the `ReactMounter` docs at https://brigade.netlify.com. It includes some sample code.

As for the `backbone.marionette` requirement. This package does have a fair number of peer dependencies because of what it was designed for. I've updated the `package.json` and docs to make all of that more clear.

Cheers,

Nickolas

**Comment by ruaneg** [comment]
@knicklabs, no problem glad to help. I will definitely give it another go and see how it works for us :)

**Comment by ruaneg** [comment]
Hi Nickolas,

That got it working alright! 

One thing Ive noticed is that the Redux store appears to be pre populated with an initial state. This state looks like its perhaps derived from one of your in house apps.

`{
  stores: {
    AssociationControlStore: {
      associationButtonStates: null,
      noAssociationButtonStates: null
    },
    AttachmentStore: {
      attachments: null
    },
    BrandStore: {
      brandStoreLocationStateMap: null,
      unsubscribeLinksMap: null,
      feedbackStateMap: null,
      relatedBrandsMap: null,
      brandTxpDataMap: null
    },
    CardFailedStateStore: {
      map: null
    },
    CardTemplateStore: {},
    ContactEditorIdsStore: {
      map: null
    },
    ContactEditorRendererStore: {
      isOpen: false,
      id: null,
      folderId: null,
      originalPersona: null,
      createCallbacks: null,
      editCallbacks: null,
      focusPropertyUri: null,
      contactEditorMode: null,
      contactEditorCorrelationId: ''
    },
 ....
}`

Gary

**Comment by knicklabs** [comment]
@ruaneg glad to hear you go it working! That's likely some state we setup for our stories / examples. I'll check it out, thanks!
